const main = document.querySelector('main');
const areas = ['All areas','Kochi','Alappuzha','Thrissur','Thiruvananthapuram'];
let selectedArea = 'All areas';
const icons = {
 phone:'<path d="M5 3h4l2 5-3 2a14 14 0 0 0 6 6l2-3 5 2v4c0 2-2 3-4 2C9 19 5 15 3 7c-1-2 0-4 2-4Z"/>',
 shelter:'<path d="m3 11 9-8 9 8M5 10v11h14V10M9 21v-7h6v7"/>',
 report:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2M9 10h6M9 14h6M9 18h4"/>',
 safety:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
 flood:'<path d="M3 17q3-4 6 0t6 0t6 0M3 21q3-4 6 0t6 0t6 0M7 13V8l5-5 5 5v5M10 13v-3h4v3"/>',
 fire:'<path d="M13 2c2 6-5 7-3 12 2 0 4-3 5-5 8 8 5 13-3 13S1 14 6 9c0 4 1 5 2 5C6 8 12 7 13 2Z"/>',
 accident:'<path d="m5 8 2-4h10l2 4 2 3v7H3v-7l2-3ZM3 11h18M6 15h2M16 15h2M5 18v3M19 18v3"/>'
};
const icon = name => `<span class="icon"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]}</svg></span>`;
const escapeHTML = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options = (list,value) => list.map(x=>`<option ${x===value?'selected':''}>${escapeHTML(x)}</option>`).join('');
const shelters = [
 {name:'Riverside Community Hall',area:'Kochi',address:'Demo address: Riverside Road, Kochi',access:'Step-free entrance (sample)',stepFree:true},
 {name:'Northside Government School',area:'Kochi',address:'Demo address: Northside Road, Kochi',access:'Not confirmed',stepFree:false},
 {name:'Lakeside Community Centre',area:'Alappuzha',address:'Demo address: Lakeside Road, Alappuzha',access:'Step-free entrance (sample)',stepFree:true},
 {name:'Central Relief Hall',area:'Thrissur',address:'Demo address: Central Road, Thrissur',access:'Not confirmed',stepFree:false},
 {name:'Southside Community Hall',area:'Thiruvananthapuram',address:'Demo address: Southside Road, Thiruvananthapuram',access:'Step-free entrance (sample)',stepFree:true}
];
const safety = {
 floods:{title:'Flood safety',icon:'flood',source:'National Disaster Management Authority — Floods',url:'https://ndma.gov.in/Natural-Hazards/Floods',steps:[['Move to higher ground.','Follow evacuation instructions from local authorities. Avoid low-lying areas.'],['Stay out of floodwater.','Do not walk or drive through flooded roads. Water can hide strong currents and damaged surfaces.'],['Keep away from electrical hazards.','Avoid fallen power lines and wet electrical equipment.'],['Take essentials if it is safe.','Carry drinking water, essential medicines, a torch and important documents. Do not delay evacuation.']]},
 fires:{title:'Fire safety',icon:'fire',source:'American Red Cross — Home Fire Safety',url:'https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/fire.html',steps:[['Get out and stay out.','Leave the building immediately. Do not stop to collect belongings or go back inside.'],['Use stairs, not lifts.','Use the nearest safe exit. Stay low if you must pass through smoke.'],['Call 112 from a safe place.','Give your location and describe what is burning.'],['Follow emergency responders.','Keep access clear for fire crews. Do not attempt an untrained rescue.']]},
 accidents:{title:'Road accident safety',icon:'accident',source:'IFRC — International First Aid, Resuscitation and Education Guidelines',url:'https://www.ifrc.org/document/international-first-aid-resuscitation-and-education-guidelines',steps:[['Check the scene for danger.','Keep yourself safe from traffic, fire and other hazards before approaching.'],['Call 112.','Give the exact location, nearby landmarks and the number of people involved. Follow the dispatcher’s instructions.'],['Avoid moving injured people.','Unless there is immediate danger, wait for trained help. Do not attempt procedures you are not trained to perform.'],['Keep the route clear.','Stay in a safe place and help responders find the location if you can do so safely.']]}
};
function read(key){try{const result=JSON.parse(localStorage.getItem('cc-'+key)||'[]');return Array.isArray(result)?result.filter(x=>x&&typeof x==='object'&&typeof x.id==='string'):[]}catch{return []}}
function write(key,items){try{localStorage.setItem('cc-'+key,JSON.stringify(items));return true}catch{toast('Could not save on this device. Check browser storage settings.');return false}}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.style.display='none',6000)}
function head(title,description){return `<a class="back" href="#home">← Back to home</a><div class="page-head"><div class="eyebrow">Help, within reach</div><h1>${title}</h1><p>${description}</p></div>`}
function disclaimer(text){return `<div class="notice"><span class="notice-icon" aria-hidden="true">ⓘ</span><p>${text}</p></div>`}
function sourceNote(){return `<div class="source-note">Safety references linked below. Last check attempted: 7 October 2026. These safety-guidance pages have not been independently rechecked; the helpline-directory check does not verify this guidance. <a href="#sources">View sources & limitations →</a></div>`}
function home(){main.innerHTML=`<div class="intro"><div><div class="eyebrow">Here when you need it</div><h1>Find help. Stay safe.</h1><p>Quick access to emergency assistance and trusted safety resources.</p></div><div class="area-widget"><label for="home-area">YOUR AREA</label><select id="home-area">${options(areas,selectedArea)}</select></div></div><div class="actions"><a class="action urgent" href="#emergency">${icon('phone')}<span class="arrow">→</span><h3>Emergency contacts</h3><p>Immediate danger?<br>Find numbers and nearby services.</p></a><a class="action" href="#shelters">${icon('shelter')}<span class="arrow">→</span><h3>Find Shelter</h3><p>Find a safer place for you and your family.</p></a><a class="action" href="#report">${icon('report')}<span class="arrow">→</span><h3>Report Incident</h3><p>Share what’s happening in your area.</p></a><a class="action" href="#safety">${icon('safety')}<span class="arrow">→</span><h3>Safety Instructions</h3><p>Know what to do.<br>One clear step at a time.</p></a></div>${disclaimer('<strong>In immediate danger? Call 112.</strong> This demo does not alert emergency services. Do not wait for a response here.')}<div class="section-heading"><div><h2>A safer next step</h2><p>Useful information, without the noise.</p></div><a class="text-link" href="#emergency">Emergency information →</a></div><div class="lower-grid"><section class="panel"><div class="panel-top"><h3>Shelters in your area</h3><span class="pill">SAMPLE DATA</span></div><div id="home-shelters"></div><div class="panel-bottom"><span>Availability is not confirmed.</span><a class="text-link" href="#shelters">View all shelters →</a></div></section><section class="panel"><div class="panel-top"><h3>Know what to do</h3></div>${Object.entries(safety).map(([key,s])=>`<a class="safety-row" href="#safety/${key}"><span class="mini-icon">${'<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[s.icon]+'</svg>'}</span><div><h3>${s.title}</h3><p>${key==='floods'?'Stay clear of water. Move to safety.':key==='fires'?'Get out. Stay out. Call for help.':'Stay safe and get trained help.'}</p></div><span>→</span></a>`).join('')}</section></div><section class="volunteer-banner"><span class="mini-icon" aria-hidden="true">♡</span><div><h3>A helping hand makes a difference.</h3><p>Offer supplies, transport or shelter support in your area.</p></div><a class="button" href="#volunteer">Offer help <span>→</span></a></section>`;const renderMini=()=>{let list=shelters.filter(x=>selectedArea==='All areas'||x.area===selectedArea).slice(0,2);document.querySelector('#home-shelters').innerHTML=list.map(x=>`<div class="shelter-mini"><span class="mini-icon" aria-hidden="true">⌂</span><div><h3>${x.name}</h3><p>${x.area} · Sample shelter</p></div><span class="status">Not confirmed</span></div>`).join('')};renderMini();document.querySelector('#home-area').onchange=e=>{selectedArea=e.target.value;renderMini()}}
function emergency(){renderEmergency(main)}
function shelterPage(){main.innerHTML=head('Find a safer place','Search sample shelters by area and accessibility. No map needed.')+disclaimer('<strong>Demo directory — every shelter is fictional.</strong> Do not travel to these addresses for assistance. Contact local authorities for actual shelters. Availability is not confirmed.')+`<div class="filters"><div><label for="search">Search shelters</label><input id="search" type="search" placeholder="Search by name, area or address"></div><div><label for="filter-area">Area</label><select id="filter-area">${options(areas,areas.includes(selectedArea)?selectedArea:'All areas')}</select></div><div><label for="filter-access">Accessibility</label><select id="filter-access"><option>All accessibility</option><option>Step-free (sample)</option><option>Not confirmed</option></select></div></div><p id="results-count" role="status" class="hint"></p><div id="shelter-results" class="shelter-list"></div>`;const filter=()=>{const query=document.querySelector('#search').value.toLowerCase().trim(),area=document.querySelector('#filter-area').value,access=document.querySelector('#filter-access').value;const list=shelters.filter(s=>(area==='All areas'||s.area===area)&&(`${s.name} ${s.area} ${s.address}`.toLowerCase().includes(query))&&(access==='All accessibility'||(access==='Step-free (sample)'?s.stepFree:!s.stepFree)));document.querySelector('#results-count').textContent=`${list.length} sample shelter${list.length===1?'':'s'} found`;document.querySelector('#shelter-results').innerHTML=list.length?list.map(s=>`<article class="panel shelter-card"><span class="pill">SAMPLE SHELTER · FICTIONAL</span><h3>${s.name}</h3><p>${s.area}</p><div class="details"><p><strong>Address:</strong> ${s.address}</p><p><strong>Accessibility:</strong> ${s.access}</p><p><strong>Availability:</strong> Not confirmed</p></div><a class="button" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(s.area+', Kerala, India')}" target="_blank" rel="noopener noreferrer">View directions to ${s.area} →</a><p class="hint">Opens directions to the area, not this fictional shelter.</p></article>`).join(''):'<div class="panel empty"><h3>No matching sample shelters</h3><p>Try another area or clear the search.</p><button class="button" id="reset-filters">Clear filters</button></div>';const reset=document.querySelector('#reset-filters');if(reset)reset.onclick=()=>{document.querySelector('#search').value='';document.querySelector('#filter-area').value='All areas';document.querySelector('#filter-access').selectedIndex=0;filter()}};['search','filter-area','filter-access'].forEach(id=>document.getElementById(id).addEventListener('input',filter));filter()}
function savedMarkup(key){const records=read(key);return records.length?records.map(r=>`<article class="saved-item"><span class="pill">${key==='reports'?'UNVERIFIED COMMUNITY REPORT':'LOCAL DEMO REGISTRATION'}</span><h3>${escapeHTML(r.type||r.category)} · ${escapeHTML(r.area||r.location)}</h3><p>${escapeHTML(r.description||'Support offered in this area.')}</p>${r.urgency?`<p>Urgency: ${escapeHTML(r.urgency)}</p>`:''}<p>Reference: ${escapeHTML(r.id)}</p><p>${escapeHTML(r.time)}</p><button class="delete" data-id="${escapeHTML(r.id)}" data-key="${key}">Delete this ${key==='reports'?'report':'registration'}</button></article>`).join(''):`<div class="empty">No saved ${key==='reports'?'reports':'registrations'} on this device yet.</div>`}
function bindDeletes(){document.querySelectorAll('[data-id]').forEach(btn=>btn.onclick=()=>{if(write(btn.dataset.key,read(btn.dataset.key).filter(r=>r.id!==btn.dataset.id))){document.querySelector('#saved').innerHTML=savedMarkup(btn.dataset.key);bindDeletes();toast('Deleted from this device.')}})}
function report(){main.innerHTML=head('Report an incident','Record what you observed. Keep details brief and avoid sharing sensitive information.')+disclaimer('<strong>This demo does not notify emergency services.</strong> Reports are saved only on this device and remain unverified. Call <a href="tel:112">112</a> for immediate danger.')+`<div id="confirmation" role="status"></div><div class="form-layout"><form id="report-form" class="panel"><div class="form-grid"><div><label for="type">Incident type</label><select id="type" required><option value="">Select a type</option>${options(['Flood','Fire','Road accident','Other'],'')}</select></div><div><label for="urgency">Urgency</label><select id="urgency" required><option value="">Select urgency</option>${options(['Immediate danger — call 112','Urgent assistance needed','Information only'],'')}</select></div><div class="full"><label for="location">Location or nearby landmark</label><input id="location" required minlength="3" maxlength="160" placeholder="e.g. Road name, landmark and town"></div><div class="full"><label for="description">Brief description</label><textarea id="description" required minlength="10" maxlength="600" placeholder="What happened? What help might be needed?"></textarea><p class="hint">10–600 characters. Do not include other people’s personal details.</p></div><div class="full"><label for="contact">Contact details <span class="hint">(optional)</span></label><input id="contact" maxlength="100" placeholder="Phone or email, if you wish"><p class="hint">Stored on this device only. No one will contact you through this demo.</p></div><div class="full"><button class="button primary" type="submit">Save unverified report →</button></div></div></form><section class="panel"><h3>Your saved reports</h3><p class="hint">Visible only in this browser. Delete any report below.</p><div id="saved">${savedMarkup('reports')}</div></section></div>`;bindDeletes();const form=document.querySelector('#report-form');form.onsubmit=e=>{e.preventDefault();if(!validateTrim(form))return;const id='CC-'+crypto.randomUUID().slice(0,8).toUpperCase();const record={id,type:form.querySelector('#type').value,urgency:form.querySelector('#urgency').value,location:form.querySelector('#location').value.trim(),description:form.querySelector('#description').value.trim(),contact:form.querySelector('#contact').value.trim(),time:new Date().toLocaleString('en-IN')};if(write('reports',[record,...read('reports')])){form.reset();document.querySelector('#confirmation').innerHTML=`<div class="success"><strong>Report saved on this device · ${id}</strong><p>This is an unverified community report. Emergency services have not been notified. For immediate danger, <a href="tel:112">call 112</a>.</p></div>`;document.querySelector('#saved').innerHTML=savedMarkup('reports');bindDeletes();document.querySelector('#confirmation').scrollIntoView({block:'start'})}}}
function validateTrim(form){for(const el of form.querySelectorAll('input[required],textarea[required]')){el.setCustomValidity(el.value.trim().length<(el.minLength>0?el.minLength:1)?'Please enter a meaningful location or description.':'');el.oninput=()=>el.setCustomValidity('')}return form.reportValidity()}
function volunteer(){main.innerHTML=head('Offer a helping hand','Support your community with supplies, transport or shelter assistance.')+disclaimer('<strong>Local demo registration only.</strong> This is not sent to any organisation. Do not enter dangerous areas or attempt rescues without training and official coordination.')+`<div id="confirmation" role="status"></div><div class="form-layout"><form class="panel" id="volunteer-form"><div class="form-grid"><div><label for="vol-area">Area</label><select id="vol-area" required><option value="">Select your area</option>${options(areas.slice(1),selectedArea)}<option>Other</option></select></div><div><label for="category">Support category</label><select id="category" required><option value="">Select support</option>${options(['Supplies','Transport','Shelter support'],'')}</select></div><div class="full"><label for="vol-note">What can you offer? <span class="hint">(optional)</span></label><textarea id="vol-note" maxlength="300" placeholder="e.g. Packaged drinking water or blankets"></textarea><p class="hint">No contact details needed. Coordinate actual help with local authorities.</p></div><div class="full"><button class="button secondary">Save demo registration →</button></div></div></form><section class="panel"><h3>Your saved registrations</h3><p class="hint">Stored in this browser only.</p><div id="saved">${savedMarkup('volunteers')}</div></section></div>`;bindDeletes();document.querySelector('#volunteer-form').onsubmit=e=>{e.preventDefault();const id='VOL-'+crypto.randomUUID().slice(0,8).toUpperCase(),r={id,area:document.querySelector('#vol-area').value,category:document.querySelector('#category').value,description:document.querySelector('#vol-note').value.trim(),time:new Date().toLocaleString('en-IN')};if(write('volunteers',[r,...read('volunteers')])){e.target.reset();document.querySelector('#confirmation').innerHTML=`<div class="success"><strong>Registration saved · ${id}</strong><p>Saved on this device only. No organisation has been notified.</p></div>`;document.querySelector('#saved').innerHTML=savedMarkup('volunteers');bindDeletes()}}}
function safetyPage(key='floods'){if(!safety[key])key='floods';const s=safety[key];main.innerHTML=head('Safety instructions','Simple steps to help you stay safe. Always follow local authorities and emergency responders.')+`<div class="safety-tabs" aria-label="Safety categories">${Object.entries(safety).map(([k,s])=>`<a class="button ${key===k?'secondary':''}" ${key===k?'aria-current="page"':''} href="#safety/${k}">${s.title}</a>`).join('')}</div><section class="panel"><h2>${s.title}</h2><ol class="steps">${s.steps.map(([a,b])=>`<li><div><strong>${a}</strong><p>${b}</p></div></li>`).join('')}</ol><div class="source-note">Source: <a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.source} →</a></div>${sourceNote()}</section>${disclaimer('In immediate danger, move to safety if possible and <a href="tel:112"><strong>call 112</strong></a>. These general steps do not replace instructions from trained responders.')}`}
function sources(){main.innerHTML=head('Sources & data transparency','Understand what is official, what is sample data, and what stays on your device.')+`<section class="panel"><h3>Official emergency contact</h3><p>112 — India’s Emergency Response Support System. Additional emergency and support contacts are listed on the emergency page, sourced from the National Portal of India (checked 7 October 2026).</p><p><a href="https://112.gov.in/" target="_blank" rel="noopener noreferrer">Government of India — ERSS →</a></p><div class="details"><p><a href="https://www.india.gov.in/directory/helpline" target="_blank" rel="noopener noreferrer">National Portal of India — Helpline directory →</a></p><h3>Safety references</h3>${Object.values(safety).map(s=>`<p><a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.source} →</a></p>`).join('')}${sourceNote()}</div><div class="details"><h3>Sample shelters</h3><p>All shelter names, addresses and accessibility details are fictional examples for the college demo. Availability is always “Not confirmed.” Directions point to the general area only.</p></div><div class="details"><h3>Reports and volunteer registrations</h3><p>Saved in this browser’s local storage. Reports are unverified. Nothing is submitted to authorities or an organisation. Delete individual records on the report and volunteer pages. Anyone using this browser profile may see saved information.</p><button class="button" id="delete-all">Delete all demo reports & registrations</button><p id="delete-feedback" role="status" class="hint"></p></div><div class="details"><h3>Connection and privacy</h3><p>No login, tracking or location request on page load. Location is requested only when you press an emergency location-search button. Coordinates are not stored by this app. A rounded search centre is sent to the public Overpass API to find OpenStreetMap facilities within 10 km. These community listings may be incomplete or outdated; phone numbers and service availability are not independently verified. External maps receive coordinates when you open a map link and have their own privacy policies. National helplines remain available without location. Nearby lookup does not alert responders.</p><p>Offline access is not implemented. Keep a phone available to call 112.</p></div></section>`;document.querySelector('#delete-all').onclick=()=>{try{localStorage.removeItem('cc-reports');localStorage.removeItem('cc-volunteers');document.querySelector('#delete-feedback').textContent='All local demo reports and registrations have been deleted.'}catch{document.querySelector('#delete-feedback').textContent='Unable to access storage. Clear this site’s data in browser settings.'}}}
function route(){const [page,key]=location.hash.slice(1).split('/');({home,emergency,shelters:shelterPage,report,volunteer,sources,safety:()=>safetyPage(key)}[page]||home)();window.scrollTo(0,0);document.title=`${{emergency:'Emergency assistance',shelters:'Find shelter',report:'Report incident',volunteer:'Offer help',sources:'Sources',safety:'Safety instructions'}[page]||'Emergency Response Hub'} — CrisisConnect`;main.setAttribute('tabindex','-1');if(location.hash)main.focus({preventScroll:true})}
window.addEventListener('hashchange',route);route();
document.querySelector('#emergency-now').onclick=()=>{if(location.hash==='#emergency'){startNearbySearch()}else{location.hash='emergency';window.addEventListener('hashchange',()=>startNearbySearch(),{once:true})}};
